###
GET http://localhost:8088/plants/getall?key=TQqqoA?p=1&l=9
###
GET http://localhost:8088/plants/getall?key=TQqqoA/1
###
GET http://localhost:8088/plants/getall?key=TQqqoA
###
DELETE  http://localhost:8088/plants/getall?key=TQqqoA
###
POST   http://localhost:8088/plants/getall?key=TQqqoA
Content-Type: application/json

    {
        "id": '4',
        "image": 'https://static.thcdn.com/images/xsmall/webp//productimg/original/13885104-6704996676979558.jpg',
        "title": 'Molton Brown Festive Bauble Gift Set', 
        "price": 40,
        "Description": 'This holiday season, discover the gift of deeply c…and
        impurities for a soft and
        glowing complexion.'

    }
